### ISSUE TITLE
Error on function call

### ISSUE THREAD

**Issue by ppssphysics** [news-r/spotlight#1]
running text_annotate on vector of text, I get the following error:
Error in pb_render(self, private, tokens) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/prettyunits/R/prettyunits.rdb' is corrupt
In addition: Warning message:
In pb_render(self, private, tokens) : internal error -3 in R_decompress1

Are these tokens inherited from dependent packages?

**Comment by ppssphysics** [comment]
Fixed by reloading session. Still curious what the message means...?

**Comment by JohnCoene** [comment]
Me too, I just learned to restart the session 🙉
